services:
  - type: web
    name: encriptador-backend
    env: python
    region: oregon
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python main_render.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"