services:
  - type: web
    name: encriptador-backend
    env: python
    region: oregon
    rootDir: .
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/main_render.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"